remote_theme: pmarsceill/just-the-docs

title: TEASPN
description: TEASPN — Framework and Protocol for Integrated Writing Assistance Environments
url: "https://www.teaspn.org" 

search_enabled: true

aux_links:
  "See TEASPN on GitHub":
    - "//github.com/teaspn/teaspn"

# Google Analytics Tracking
ga_tracking: UA-175204-21

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
